# Generated by Django 5.1.4 on 2025-01-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='datasets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('columns', models.JSONField(null=True)),
                ('numeric_columns', models.JSONField(null=True)),
                ('categorical_columns', models.JSONField(null=True)),
                ('row_count', models.IntegerField(null=True)),
            ],
        ),
    ]
